from phishing_domain_detector.component.data_ingestion import DataIngestion
from phishing_domain_detector.component.data_validation import DataValidation
from phishing_domain_detector.component.data_transformation import DataTransformation
from phishing_domain_detector.component.model_trainer import ModelTrainer